#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with Fizz, Buzz, and FizzBuzz substitutions

for _ in {1..100}; do
    if [ $(( _ % 15 )) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $(( _ % 3 )) -eq 0 ]; then
        echo "Fizz"
    elif [ $(( _ % 5 )) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$_"
    fi
done

