#!/usr/bin/env bash
# This script reads /etc/passwd and tells a story about each user

while IFS=: read -r username password uid gid full_name home_dir shell
do
  echo "The user $username is part of the $gid gang, lives in $username and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd

