#!/usr/bin/env bash
# This script groups Apache log entries by IP and HTTP status code and counts occurrences

awk '{count[$1" "$9]++} END {for (i in count) printf "%6d %s\n", count[i], i}' apache-access.log | sort -rn

