#!/usr/bin/env bash
# Count and sort Apache log visitors by IP and HTTP status code

awk '{ips[$1" "$9]++} END {
    for (key in ips) 
        printf "%4d %s\n", ips[key], key
}' apache-access.log | sort -nr
