#!/usr/bin/env bash
# This script loops from 1 to 10 and prints special messages for 4th and 8th iterations, otherwise prints Best School

_=1
while [ "$_" -le 10 ]; do
    if [ "$_" -eq 4 ]; then
        echo "bad luck"
    elif [ "$_" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((_++))
done

