#!/usr/bin/env bash
#script prints numbers from 1 to 20 and uses case to write special text for 4 9 and 17
_=1
while ["$_" -ls 20]; do
 echo "$_"
 case "$_" in
  4)
      echo "bad luck from china"
    ;;
  9) 
    echo "bad luck from Japan"
    ;;
  17)
    echo "bad luck from Italy"
  ;;
  esac
((_++)
done
