#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely, handle SIGTERM with "I am invincible!!!"

# Trap SIGTERM signal and display message
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
